apiVersion: apps/v1
kind: Deployment
metadata:
  name: globeco-execution-service
  namespace: globeco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: globeco-execution-service
  template:
    metadata:
      labels:
        app: globeco-execution-service
    spec:
      containers:
        - name: globeco-execution-service
          image: kasbench/globeco-execution-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 240
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health/readiness  
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      restartPolicy: Always
---
