apiVersion: v1
kind: Service
metadata:
  name: globeco-execution-service
  namespace: globeco
spec:
  selector:
    app: globeco-execution-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP 